// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"

	kpuManager "github.com/nocturna-ta/votechain-contract/binding/kpuManager"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// KpuManagerInterface is an autogenerated mock type for the KpuManagerInterface type
type KpuManagerInterface struct {
	mock.Mock
}

// DeactivateKPUKota provides a mock function with given fields: opts, Address
func (_m *KpuManagerInterface) DeactivateKPUKota(opts *bind.TransactOpts, Address common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, Address)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateKPUKota")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, Address)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) *types.Transaction); ok {
		r0 = rf(opts, Address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address) error); ok {
		r1 = rf(opts, Address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateKPUProvinsi provides a mock function with given fields: opts, Address
func (_m *KpuManagerInterface) DeactivateKPUProvinsi(opts *bind.TransactOpts, Address common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, Address)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateKPUProvinsi")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, Address)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) *types.Transaction); ok {
		r0 = rf(opts, Address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address) error); ok {
		r1 = rf(opts, Address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllKPUKota provides a mock function with given fields: opts
func (_m *KpuManagerInterface) GetAllKPUKota(opts *bind.CallOpts) ([]kpuManager.IKPUManagerKPUKota, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUKota")
	}

	var r0 []kpuManager.IKPUManagerKPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) ([]kpuManager.IKPUManagerKPUKota, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) []kpuManager.IKPUManagerKPUKota); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]kpuManager.IKPUManagerKPUKota)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllKPUProvinsi provides a mock function with given fields: opts
func (_m *KpuManagerInterface) GetAllKPUProvinsi(opts *bind.CallOpts) ([]kpuManager.IKPUManagerKPUProvinsi, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKPUProvinsi")
	}

	var r0 []kpuManager.IKPUManagerKPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) ([]kpuManager.IKPUManagerKPUProvinsi, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) []kpuManager.IKPUManagerKPUProvinsi); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]kpuManager.IKPUManagerKPUProvinsi)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKpuKotaByAddress provides a mock function with given fields: opts, Address
func (_m *KpuManagerInterface) GetKpuKotaByAddress(opts *bind.CallOpts, Address common.Address) (kpuManager.IKPUManagerKPUKota, error) {
	ret := _m.Called(opts, Address)

	if len(ret) == 0 {
		panic("no return value specified for GetKpuKotaByAddress")
	}

	var r0 kpuManager.IKPUManagerKPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (kpuManager.IKPUManagerKPUKota, error)); ok {
		return rf(opts, Address)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) kpuManager.IKPUManagerKPUKota); ok {
		r0 = rf(opts, Address)
	} else {
		r0 = ret.Get(0).(kpuManager.IKPUManagerKPUKota)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, Address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKpuKotaRegion provides a mock function with given fields: opts, kpuAddress
func (_m *KpuManagerInterface) GetKpuKotaRegion(opts *bind.CallOpts, kpuAddress common.Address) (string, error) {
	ret := _m.Called(opts, kpuAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetKpuKotaRegion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (string, error)); ok {
		return rf(opts, kpuAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) string); ok {
		r0 = rf(opts, kpuAddress)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, kpuAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKpuProvinsiByAddress provides a mock function with given fields: opts, Address
func (_m *KpuManagerInterface) GetKpuProvinsiByAddress(opts *bind.CallOpts, Address common.Address) (kpuManager.IKPUManagerKPUProvinsi, error) {
	ret := _m.Called(opts, Address)

	if len(ret) == 0 {
		panic("no return value specified for GetKpuProvinsiByAddress")
	}

	var r0 kpuManager.IKPUManagerKPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (kpuManager.IKPUManagerKPUProvinsi, error)); ok {
		return rf(opts, Address)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) kpuManager.IKPUManagerKPUProvinsi); ok {
		r0 = rf(opts, Address)
	} else {
		r0 = ret.Get(0).(kpuManager.IKPUManagerKPUProvinsi)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, Address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsKPUKota provides a mock function with given fields: opts, kpuAddress
func (_m *KpuManagerInterface) IsKPUKota(opts *bind.CallOpts, kpuAddress common.Address) (bool, error) {
	ret := _m.Called(opts, kpuAddress)

	if len(ret) == 0 {
		panic("no return value specified for IsKPUKota")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (bool, error)); ok {
		return rf(opts, kpuAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) bool); ok {
		r0 = rf(opts, kpuAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, kpuAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsKPUProvinsi provides a mock function with given fields: opts, kpuAddress
func (_m *KpuManagerInterface) IsKPUProvinsi(opts *bind.CallOpts, kpuAddress common.Address) (bool, error) {
	ret := _m.Called(opts, kpuAddress)

	if len(ret) == 0 {
		panic("no return value specified for IsKPUProvinsi")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (bool, error)); ok {
		return rf(opts, kpuAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) bool); ok {
		r0 = rf(opts, kpuAddress)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, kpuAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KpuKota provides a mock function with given fields: opts, addr
func (_m *KpuManagerInterface) KpuKota(opts *bind.CallOpts, addr common.Address) (kpuManager.IKPUManagerKPUKota, error) {
	ret := _m.Called(opts, addr)

	if len(ret) == 0 {
		panic("no return value specified for KpuKota")
	}

	var r0 kpuManager.IKPUManagerKPUKota
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (kpuManager.IKPUManagerKPUKota, error)); ok {
		return rf(opts, addr)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) kpuManager.IKPUManagerKPUKota); ok {
		r0 = rf(opts, addr)
	} else {
		r0 = ret.Get(0).(kpuManager.IKPUManagerKPUKota)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KpuProvinsi provides a mock function with given fields: opts, addr
func (_m *KpuManagerInterface) KpuProvinsi(opts *bind.CallOpts, addr common.Address) (kpuManager.IKPUManagerKPUProvinsi, error) {
	ret := _m.Called(opts, addr)

	if len(ret) == 0 {
		panic("no return value specified for KpuProvinsi")
	}

	var r0 kpuManager.IKPUManagerKPUProvinsi
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (kpuManager.IKPUManagerKPUProvinsi, error)); ok {
		return rf(opts, addr)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) kpuManager.IKPUManagerKPUProvinsi); ok {
		r0 = rf(opts, addr)
	} else {
		r0 = ret.Get(0).(kpuManager.IKPUManagerKPUProvinsi)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUKota provides a mock function with given fields: opts, Address, name, region
func (_m *KpuManagerInterface) RegisterKPUKota(opts *bind.TransactOpts, Address common.Address, name string, region string) (*types.Transaction, error) {
	ret := _m.Called(opts, Address, name, region)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUKota")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) (*types.Transaction, error)); ok {
		return rf(opts, Address, name, region)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) *types.Transaction); ok {
		r0 = rf(opts, Address, name, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address, string, string) error); ok {
		r1 = rf(opts, Address, name, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUProvinsi provides a mock function with given fields: opts, Address, name, region
func (_m *KpuManagerInterface) RegisterKPUProvinsi(opts *bind.TransactOpts, Address common.Address, name string, region string) (*types.Transaction, error) {
	ret := _m.Called(opts, Address, name, region)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUProvinsi")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) (*types.Transaction, error)); ok {
		return rf(opts, Address, name, region)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) *types.Transaction); ok {
		r0 = rf(opts, Address, name, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address, string, string) error); ok {
		r1 = rf(opts, Address, name, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKpuManagerInterface creates a new instance of KpuManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKpuManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *KpuManagerInterface {
	mock := &KpuManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
