// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"

	voterManager "github.com/nocturna-ta/votechain-contract/binding/voterManager"
)

// VoterManagerInterface is an autogenerated mock type for the VoterManagerInterface type
type VoterManagerInterface struct {
	mock.Mock
}

// GetAllVoter provides a mock function with given fields: opts
func (_m *VoterManagerInterface) GetAllVoter(opts *bind.CallOpts) (*[]voterManager.IVoterManagerVoter, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVoter")
	}

	var r0 *[]voterManager.IVoterManagerVoter
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (*[]voterManager.IVoterManagerVoter, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) *[]voterManager.IVoterManagerVoter); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]voterManager.IVoterManagerVoter)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByAddress provides a mock function with given fields: opts, voterAddress
func (_m *VoterManagerInterface) GetVoterByAddress(opts *bind.CallOpts, voterAddress common.Address) (*voterManager.IVoterManagerVoter, error) {
	ret := _m.Called(opts, voterAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByAddress")
	}

	var r0 *voterManager.IVoterManagerVoter
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (*voterManager.IVoterManagerVoter, error)); ok {
		return rf(opts, voterAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) *voterManager.IVoterManagerVoter); ok {
		r0 = rf(opts, voterAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*voterManager.IVoterManagerVoter)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, voterAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByNIK provides a mock function with given fields: opts, nik
func (_m *VoterManagerInterface) GetVoterByNIK(opts *bind.CallOpts, nik string) (*voterManager.IVoterManagerVoter, error) {
	ret := _m.Called(opts, nik)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByNIK")
	}

	var r0 *voterManager.IVoterManagerVoter
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, string) (*voterManager.IVoterManagerVoter, error)); ok {
		return rf(opts, nik)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, string) *voterManager.IVoterManagerVoter); ok {
		r0 = rf(opts, nik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*voterManager.IVoterManagerVoter)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, string) error); ok {
		r1 = rf(opts, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterByRegion provides a mock function with given fields: opts, region
func (_m *VoterManagerInterface) GetVoterByRegion(opts *bind.CallOpts, region string) (*[]voterManager.IVoterManagerVoter, error) {
	ret := _m.Called(opts, region)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterByRegion")
	}

	var r0 *[]voterManager.IVoterManagerVoter
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, string) (*[]voterManager.IVoterManagerVoter, error)); ok {
		return rf(opts, region)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, string) *[]voterManager.IVoterManagerVoter); ok {
		r0 = rf(opts, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]voterManager.IVoterManagerVoter)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, string) error); ok {
		r1 = rf(opts, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVoterNikByAddress provides a mock function with given fields: opts, voterAddress
func (_m *VoterManagerInterface) GetVoterNikByAddress(opts *bind.CallOpts, voterAddress common.Address) (string, error) {
	ret := _m.Called(opts, voterAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetVoterNikByAddress")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (string, error)); ok {
		return rf(opts, voterAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) string); ok {
		r0 = rf(opts, voterAddress)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, voterAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KpuManager provides a mock function with given fields: opts
func (_m *VoterManagerInterface) KpuManager(opts *bind.CallOpts) (common.Address, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for KpuManager")
	}

	var r0 common.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) (common.Address, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts) common.Address); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkVoted provides a mock function with given fields: opts, voterAddress
func (_m *VoterManagerInterface) MarkVoted(opts *bind.TransactOpts, voterAddress common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, voterAddress)

	if len(ret) == 0 {
		panic("no return value specified for MarkVoted")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, voterAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) *types.Transaction); ok {
		r0 = rf(opts, voterAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address) error); ok {
		r1 = rf(opts, voterAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterVoter provides a mock function with given fields: opts, nik, voterAddress
func (_m *VoterManagerInterface) RegisterVoter(opts *bind.TransactOpts, nik string, voterAddress common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, nik, voterAddress)

	if len(ret) == 0 {
		panic("no return value specified for RegisterVoter")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, nik, voterAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, common.Address) *types.Transaction); ok {
		r0 = rf(opts, nik, voterAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, common.Address) error); ok {
		r1 = rf(opts, nik, voterAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoterNIKByAddress provides a mock function with given fields: opts, voter
func (_m *VoterManagerInterface) VoterNIKByAddress(opts *bind.CallOpts, voter common.Address) (string, error) {
	ret := _m.Called(opts, voter)

	if len(ret) == 0 {
		panic("no return value specified for VoterNIKByAddress")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (string, error)); ok {
		return rf(opts, voter)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) string); ok {
		r0 = rf(opts, voter)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, voter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoterNIKByAddresses provides a mock function with given fields: opts, arg0
func (_m *VoterManagerInterface) VoterNIKByAddresses(opts *bind.CallOpts, arg0 common.Address) (string, error) {
	ret := _m.Called(opts, arg0)

	if len(ret) == 0 {
		panic("no return value specified for VoterNIKByAddresses")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) (string, error)); ok {
		return rf(opts, arg0)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, common.Address) string); ok {
		r0 = rf(opts, arg0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, common.Address) error); ok {
		r1 = rf(opts, arg0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Voters provides a mock function with given fields: opts, nik
func (_m *VoterManagerInterface) Voters(opts *bind.CallOpts, nik string) (*voterManager.IVoterManagerVoter, error) {
	ret := _m.Called(opts, nik)

	if len(ret) == 0 {
		panic("no return value specified for Voters")
	}

	var r0 *voterManager.IVoterManagerVoter
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, string) (*voterManager.IVoterManagerVoter, error)); ok {
		return rf(opts, nik)
	}
	if rf, ok := ret.Get(0).(func(*bind.CallOpts, string) *voterManager.IVoterManagerVoter); ok {
		r0 = rf(opts, nik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*voterManager.IVoterManagerVoter)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.CallOpts, string) error); ok {
		r1 = rf(opts, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVoterManagerInterface creates a new instance of VoterManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoterManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoterManagerInterface {
	mock := &VoterManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
