// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// VotechainInterface is an autogenerated mock type for the VotechainInterface type
type VotechainInterface struct {
	mock.Mock
}

// AddElection provides a mock function with given fields: opts, electionId, electionNo
func (_m *VotechainInterface) AddElection(opts *bind.TransactOpts, electionId string, electionNo string) (*types.Transaction, error) {
	ret := _m.Called(opts, electionId, electionNo)

	if len(ret) == 0 {
		panic("no return value specified for AddElection")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string) (*types.Transaction, error)); ok {
		return rf(opts, electionId, electionNo)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string) *types.Transaction); ok {
		r0 = rf(opts, electionId, electionNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, string) error); ok {
		r1 = rf(opts, electionId, electionNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUKota provides a mock function with given fields: opts, Address, name, region
func (_m *VotechainInterface) RegisterKPUKota(opts *bind.TransactOpts, Address common.Address, name string, region string) (*types.Transaction, error) {
	ret := _m.Called(opts, Address, name, region)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUKota")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) (*types.Transaction, error)); ok {
		return rf(opts, Address, name, region)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) *types.Transaction); ok {
		r0 = rf(opts, Address, name, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address, string, string) error); ok {
		r1 = rf(opts, Address, name, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUProvinsi provides a mock function with given fields: opts, Address, name, region
func (_m *VotechainInterface) RegisterKPUProvinsi(opts *bind.TransactOpts, Address common.Address, name string, region string) (*types.Transaction, error) {
	ret := _m.Called(opts, Address, name, region)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUProvinsi")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) (*types.Transaction, error)); ok {
		return rf(opts, Address, name, region)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) *types.Transaction); ok {
		r0 = rf(opts, Address, name, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address, string, string) error); ok {
		r1 = rf(opts, Address, name, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterVoter provides a mock function with given fields: opts, nik, voterAddress
func (_m *VotechainInterface) RegisterVoter(opts *bind.TransactOpts, nik string, voterAddress common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, nik, voterAddress)

	if len(ret) == 0 {
		panic("no return value specified for RegisterVoter")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, nik, voterAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, common.Address) *types.Transaction); ok {
		r0 = rf(opts, nik, voterAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, common.Address) error); ok {
		r1 = rf(opts, nik, voterAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetKpuAdmin provides a mock function with given fields: opts, newAdmin
func (_m *VotechainInterface) SetKpuAdmin(opts *bind.TransactOpts, newAdmin common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, newAdmin)

	if len(ret) == 0 {
		panic("no return value specified for SetKpuAdmin")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, newAdmin)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) *types.Transaction); ok {
		r0 = rf(opts, newAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address) error); ok {
		r1 = rf(opts, newAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetVotingStatus provides a mock function with given fields: opts, status
func (_m *VotechainInterface) SetVotingStatus(opts *bind.TransactOpts, status bool) (*types.Transaction, error) {
	ret := _m.Called(opts, status)

	if len(ret) == 0 {
		panic("no return value specified for SetVotingStatus")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, bool) (*types.Transaction, error)); ok {
		return rf(opts, status)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, bool) *types.Transaction); ok {
		r0 = rf(opts, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, bool) error); ok {
		r1 = rf(opts, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleElectionActive provides a mock function with given fields: opts, electionId, electionNo
func (_m *VotechainInterface) ToggleElectionActive(opts *bind.TransactOpts, electionId string, electionNo string) (*types.Transaction, error) {
	ret := _m.Called(opts, electionId, electionNo)

	if len(ret) == 0 {
		panic("no return value specified for ToggleElectionActive")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string) (*types.Transaction, error)); ok {
		return rf(opts, electionId, electionNo)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string) *types.Transaction); ok {
		r0 = rf(opts, electionId, electionNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, string) error); ok {
		r1 = rf(opts, electionId, electionNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Vote provides a mock function with given fields: opts, electionId, electionNo
func (_m *VotechainInterface) Vote(opts *bind.TransactOpts, electionId string, electionNo string) (*types.Transaction, error) {
	ret := _m.Called(opts, electionId, electionNo)

	if len(ret) == 0 {
		panic("no return value specified for Vote")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string) (*types.Transaction, error)); ok {
		return rf(opts, electionId, electionNo)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string) *types.Transaction); ok {
		r0 = rf(opts, electionId, electionNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, string) error); ok {
		r1 = rf(opts, electionId, electionNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVotechainInterface creates a new instance of VotechainInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVotechainInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VotechainInterface {
	mock := &VotechainInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
