// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// IVotechainTransactor is an autogenerated mock type for the IVotechainTransactor type
type IVotechainTransactor struct {
	mock.Mock
}

// AddCandidate provides a mock function with given fields: opts, candidateId, name, candidateNo
func (_m *IVotechainTransactor) AddCandidate(opts *bind.TransactOpts, candidateId string, name string, candidateNo string) (*types.Transaction, error) {
	ret := _m.Called(opts, candidateId, name, candidateNo)

	if len(ret) == 0 {
		panic("no return value specified for AddCandidate")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string, string) (*types.Transaction, error)); ok {
		return rf(opts, candidateId, name, candidateNo)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, string, string) *types.Transaction); ok {
		r0 = rf(opts, candidateId, name, candidateNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, string, string) error); ok {
		r1 = rf(opts, candidateId, name, candidateNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeactivateKPUBranch provides a mock function with given fields: opts, branchAddress
func (_m *IVotechainTransactor) DeactivateKPUBranch(opts *bind.TransactOpts, branchAddress common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, branchAddress)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateKPUBranch")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, branchAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) *types.Transaction); ok {
		r0 = rf(opts, branchAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address) error); ok {
		r1 = rf(opts, branchAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterKPUBranch provides a mock function with given fields: opts, branchAddress, name, region
func (_m *IVotechainTransactor) RegisterKPUBranch(opts *bind.TransactOpts, branchAddress common.Address, name string, region string) (*types.Transaction, error) {
	ret := _m.Called(opts, branchAddress, name, region)

	if len(ret) == 0 {
		panic("no return value specified for RegisterKPUBranch")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) (*types.Transaction, error)); ok {
		return rf(opts, branchAddress, name, region)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address, string, string) *types.Transaction); ok {
		r0 = rf(opts, branchAddress, name, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address, string, string) error); ok {
		r1 = rf(opts, branchAddress, name, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterVoter provides a mock function with given fields: opts, nik, voterAddress
func (_m *IVotechainTransactor) RegisterVoter(opts *bind.TransactOpts, nik string, voterAddress common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, nik, voterAddress)

	if len(ret) == 0 {
		panic("no return value specified for RegisterVoter")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, nik, voterAddress)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string, common.Address) *types.Transaction); ok {
		r0 = rf(opts, nik, voterAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string, common.Address) error); ok {
		r1 = rf(opts, nik, voterAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetKpuAdmin provides a mock function with given fields: opts, newAdmin
func (_m *IVotechainTransactor) SetKpuAdmin(opts *bind.TransactOpts, newAdmin common.Address) (*types.Transaction, error) {
	ret := _m.Called(opts, newAdmin)

	if len(ret) == 0 {
		panic("no return value specified for SetKpuAdmin")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) (*types.Transaction, error)); ok {
		return rf(opts, newAdmin)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, common.Address) *types.Transaction); ok {
		r0 = rf(opts, newAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, common.Address) error); ok {
		r1 = rf(opts, newAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetVotingStatus provides a mock function with given fields: opts, status
func (_m *IVotechainTransactor) SetVotingStatus(opts *bind.TransactOpts, status bool) (*types.Transaction, error) {
	ret := _m.Called(opts, status)

	if len(ret) == 0 {
		panic("no return value specified for SetVotingStatus")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, bool) (*types.Transaction, error)); ok {
		return rf(opts, status)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, bool) *types.Transaction); ok {
		r0 = rf(opts, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, bool) error); ok {
		r1 = rf(opts, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleCandidateActive provides a mock function with given fields: opts, candidateId
func (_m *IVotechainTransactor) ToggleCandidateActive(opts *bind.TransactOpts, candidateId string) (*types.Transaction, error) {
	ret := _m.Called(opts, candidateId)

	if len(ret) == 0 {
		panic("no return value specified for ToggleCandidateActive")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string) (*types.Transaction, error)); ok {
		return rf(opts, candidateId)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string) *types.Transaction); ok {
		r0 = rf(opts, candidateId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string) error); ok {
		r1 = rf(opts, candidateId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Vote provides a mock function with given fields: opts, candidateId
func (_m *IVotechainTransactor) Vote(opts *bind.TransactOpts, candidateId string) (*types.Transaction, error) {
	ret := _m.Called(opts, candidateId)

	if len(ret) == 0 {
		panic("no return value specified for Vote")
	}

	var r0 *types.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string) (*types.Transaction, error)); ok {
		return rf(opts, candidateId)
	}
	if rf, ok := ret.Get(0).(func(*bind.TransactOpts, string) *types.Transaction); ok {
		r0 = rf(opts, candidateId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*bind.TransactOpts, string) error); ok {
		r1 = rf(opts, candidateId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIVotechainTransactor creates a new instance of IVotechainTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIVotechainTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *IVotechainTransactor {
	mock := &IVotechainTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
